Repository Cratis/Chronicle, pull requests merged in 2023-12, with the labels that each got.

#1034 Fix/queries
  Source/Clients/Specifications/Projections/ImmedidateProjectionSpecificationFor.cs
  Source/Clients/Specifications/Projections/ProjectionSpecificationContext.cs
  Source/Kernel/MongoDB/EventSequences/EventSequenceQueries.cs
  Source/Kernel/MongoDB/EventSequences/MongoDBEventSequenceStorage.cs
Labels: patch

#1035 removing .Value from the GTE/LTE queries. This seems to be wrong
  Source/Kernel/MongoDB/EventSequences/EventSequenceQueries.cs
  Source/Kernel/MongoDB/EventSequences/MongoDBEventSequenceStorage.cs
Labels: patch

#1039 Removing Json serializer options - not needed
  Source/Kernel/MongoDB/Operations/MongoDBRecommendationStorage.cs
Labels: patch

#1040 Fix/state-serialization
  Source/Kernel/MongoDB/Jobs/MongoDBJobStepStorage.cs
  Source/Kernel/MongoDB/Jobs/MongoDBJobStorage.cs
  Source/Kernel/MongoDB/Operations/MongoDBRecommendationStorage.cs
Labels: patch

#1041 Fix/job-serialization
  .vscode/settings.json
  Directory.Packages.props
  Samples/Basic/CartReducer.cs
  Samples/Basic/ItemAddedToCart.cs
  Samples/Basic/Order.cs
  Samples/Basic/Program.cs
  Source/Clients/DotNET/Reducers/ReducerExtensionMethods.cs
  Source/Infrastructure/Json/TypeWithObjectPropertiesJsonConverter.cs
  Source/Infrastructure/Json/TypeWithObjectPropertiesJsonConverterFactory.cs
  Source/Infrastructure/Reflection/TypeExtensions.cs
  Source/Infrastructure/Schemas/ReflectionService.cs
  Source/Kernel/Grains.Interfaces/Jobs/IJob.cs
  Source/Kernel/Grains.Interfaces/Jobs/IJobState.cs
  Source/Kernel/Grains.Interfaces/Jobs/IJobsManager.cs
  Source/Kernel/Grains.Interfaces/Jobs/JobState.cs
  Source/Kernel/Grains/Jobs/Job.cs
  Source/Kernel/Grains/Jobs/JobStep.cs
  Source/Kernel/Grains/Jobs/JobsManager.cs
  Source/Kernel/Grains/Observation/Clients/ClientObserverSubscriber.cs
  Source/Kernel/Grains/Observation/Jobs/CatchUpObserver.cs
  Source/Kernel/Grains/Observation/Jobs/CatchUpObserverState.cs
  Source/Kernel/Grains/Observation/Jobs/ConsolidateStateForObservers.cs
  Source/Kernel/Grains/Observation/Jobs/ReplayObserver.cs
  Source/Kernel/Grains/Observation/Jobs/ReplayObserverPartition.cs
  Source/Kernel/Grains/Observation/Jobs/ReplayObserverState.cs
  Source/Kernel/Grains/Observation/Jobs/RetryFailedPartitionJob.cs
  Source/Kernel/Grains/Observation/Observer.cs
  Source/Kernel/Grains/Observation/Reducers/Clients/ClientReducerSubscriber.cs
  Source/Kernel/Grains/Observation/States/CatchUp.cs
  Source/Kernel/Grains/Observation/States/Replay.cs
  Source/Kernel/Grains/Observation/States/ResumeReplay.cs
  Source/Kernel/MongoDB/BsonValueExtensions.cs
  Source/Kernel/MongoDB/Jobs/MongoDBJobStepStorage.cs
  Source/Kernel/MongoDB/Jobs/MongoDBJobStorage.cs
  Source/Kernel/MongoDB/JsonElementSerializer.cs
  Source/Kernel/MongoDB/Recommendations/MongoDBRecommendationStorage.cs
  Source/Kernel/MongoDB/SiloBuilderExtensions.cs
  Source/Kernel/MongoDB/UriSerializer.cs
  Source/Kernel/Persistence/Jobs/IJobStorage.cs
  Source/Kernel/Persistence/Jobs/JobGrainStorageProvider.cs
  Source/Kernel/Persistence/Operations/RecommendationGrainStorageProvider.cs
  Source/Kernel/Read/Jobs/Jobs.cs
  Source/Kernel/Server/Serialization/JobStateJsonConverter.cs
  Source/Kernel/Server/Serialization/JobStepStateJsonConverter.cs
  Source/Kernel/Server/Serialization/ObserverSubscriberContextJsonConverter.cs
  Source/Kernel/Server/Serialization/ObserverSubscriptionJsonConverter.cs
  Source/Kernel/Server/Serialization/SerializationConfigurationExtensions.cs
  Source/Kernel/Server/Serialization/TypeJsonConverter.cs
  Source/Kernel/Shared/Clients/ConnectedClient.cs
  Source/Workbench/API/events/store/jobs/JobState.ts
  Specifications/Infrastructure/Json/for_TypeWithObjectPropertiesJsonConverter/Converter.cs
  Specifications/Infrastructure/Json/for_TypeWithObjectPropertiesJsonConverter/FirstType.cs
  Specifications/Infrastructure/Json/for_TypeWithObjectPropertiesJsonConverter/OtherType.cs
  Specifications/Infrastructure/Json/for_TypeWithObjectPropertiesJsonConverter/SuperType.cs
  Specifications/Infrastructure/Json/for_TypeWithObjectPropertiesJsonConverter/TypeWithObjectProperties.cs
  Specifications/Infrastructure/Json/for_TypeWithObjectPropertiesJsonConverter/when_serializing_and_deserializing_object.cs
Labels: patch

#1042 Fixing compiler errors and broken specs after internal API changes
  Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/given/a_catchup_observer_and_a_request.cs
  Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_asking_if_can_resume/and_it_is_not_subscribed.cs
  Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_asking_if_can_resume/and_it_is_subscribed.cs
  Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_completed.cs
  Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_preparing_steps.cs
  Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_step_completes.cs
  Specifications/Kernel/Grains/Observation/States/for_CatchUp/given/a_catch_up_state.cs
  Specifications/Kernel/Grains/Observation/States/for_CatchUp/when_entering/and_a_catch_up_is_already_running.cs
  Specifications/Kernel/Grains/Observation/States/for_CatchUp/when_entering/and_a_paused_catch_up_job_exists.cs
  Specifications/Kernel/Grains/Observation/States/for_CatchUp/when_entering/and_no_jobs_are_running.cs
  Specifications/Kernel/Grains/Observation/States/for_Replay/given/a_replay_state.cs
  Specifications/Kernel/Grains/Observation/States/for_Replay/when_entering/and_a_paused_replay_job_exists.cs
  Specifications/Kernel/Grains/Observation/States/for_Replay/when_entering/and_a_replay_job_is_already_running.cs
  Specifications/Kernel/Grains/Observation/States/for_Replay/when_leaving/and_a_replay_job_is_already_running.cs
Labels: patch

#1043 Fix/nullable-primitives
  .vscode/launch.json
  Samples/Basic/ItemAddedToCart.cs
  Samples/Basic/Order.cs
  Samples/Basic/Program.cs
  Source/Infrastructure/Schemas/NullableAttribute.cs
  Source/Infrastructure/Schemas/ReflectionService.cs
  Source/Infrastructure/Schemas/TypeFormatSchemaProcessor.cs
Labels: patch

#1044 Moving configuration of the CPU bound workers
  Source/Kernel/Server/CpuBoundWorkersExtensions.cs
  Source/Kernel/Server/Program.cs
Labels: patch

#1045 Binding the LimitedConcurrencyLevelTaskScheduler as a Singleton
  Source/Kernel/Server/CpuBoundWorkersExtensions.cs
Labels: patch

#1046 Lazily create the task scheduler on first access
  Source/Kernel/Grains/Workers/CpuBoundWorker.cs
Labels: patch

#1048 Stopping the rehydrate from failing during startup - but output the error
  Source/Kernel/Grains/EventSequences/EventSequences.cs
  Source/Kernel/Grains/EventSequences/EventSequencesLogMessages.cs
Labels: patch

#1049 Ensuring execution context is correct
  Source/Kernel/Grains/EventSequences/EventSequences.cs
  Source/Kernel/Server/BootProcedure.cs
  Source/Kernel/Server/log.txt
Labels: patch

#1050 If there are no status changes - show [N/A] on start time
  Source/Workbench/eventStore/Jobs.tsx
Labels: patch

#1060 Make eventTypes optional, as it should be.
  Source/Kernel/Read/EventSequences/EventSequence.cs
Labels: minor

#1061 Add REST endpoint to fetch a defined range of appended events
  Source/Kernel/Read/EventSequences/EventSequence.cs
  Source/Workbench/API/events/store/sequence/GetAppendedEventsRange.ts
Labels: minor

#1062 Fixed release build error
  Source/Kernel/Read/EventSequences/EventSequence.cs
Labels: patch, chore
